# Generated by Django 5.0.7 on 2024-09-15 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_project', '0026_remove_room_student_room_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='STUDENT',
        ),
        migrations.AddField(
            model_name='room',
            name='STUDENT',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostel_project.student'),
        ),
    ]
