# Generated by Django 5.0.7 on 2024-09-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_project', '0027_remove_room_student_room_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='STUDENT',
        ),
        migrations.AddField(
            model_name='room',
            name='STUDENTS',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='hostel_project.student'),
        ),
    ]
