# Generated by Django 5.0.7 on 2024-09-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_project', '0028_remove_room_student_room_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localmovement',
            name='entry_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
