# Generated by Django 5.0.7 on 2024-10-13 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_project', '0029_alter_localmovement_entry_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='NOTIFICATION',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hostel_project.notification'),
            preserve_default=False,
        ),
    ]
