# Generated by Django 5.0.7 on 2024-10-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_project', '0031_alter_room_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
