# Generated by Django 5.0.7 on 2024-10-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_project', '0032_alter_room_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='warden',
            name='date_of_retirement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warden',
            name='is_retired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='warden',
            name='reason_for_retirement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
