# Generated by Django 5.0.7 on 2024-10-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_project', '0034_remove_complaint_replied_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='user_type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
