# Generated by Django 5.0.7 on 2024-10-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_project', '0036_payment_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='is_retired',
            field=models.BooleanField(default=False),
        ),
    ]
