# Generated by Django 5.0.7 on 2024-10-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_project', '0037_tutor_is_retired'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='date_of_retirement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='reason_for_retirement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
